### ISSUE TITLE
Not a bug, but a question.

### ISSUE THREAD

**Issue by mariusberget92** [translized/translized-cli#2]
I have three different root views for my application, and to separate each language file I thought it would be nice to have a language folder setup like this: 

```
lang
  auth
    en.json
  dashboard
    en.json
  app
    en.json
```

Im pretty bad at explaining, but I want to have different translation files based on where I am in my application. I feel that is easier to maintain and a bit easier to read. My current config file is below, but that only works for a single file/folder.

```---
:translized:
  :access_token: ###
  :project_id: ###
  :download:
    :path: './resources/js/lang/<locale_code>.json'
    :file_format: json
    options:
      transform_placeholders_iOS_android: true
      replace_empty:
        :primary_translations: true
  :upload:
    :path: './resources/js/lang/en.json'
    :language_code: en
```

**Comment by tomovicn** [comment]
Hello @mariusberget92 ,

Currently, we don't support exporting one language into multiple files.

However, we will consider adding this feature in the future.

Thanks for your feedback.

**Comment by tomovicn** [comment]
Hey, @mariusberget92, this feature is enabled with the latest CLI release.
Here you can find examples and explanations: https://docs.translized.com/docs/cli/configuration

**Comment by mariusberget92** [comment]
Cool, will take a look. :)
